### ISSUE TITLE
General feedback 

### ISSUE THREAD

**Issue by frkbustad** [maciaslab/htsdsf_explorer#1]
Hi! I have been using the original DSF-analysis program created at UiB for 10 years + in Aurora Martinez's group. I have some immediate suggestions after first-time use:

1. Filename needs to be without space. This is not obvious for non-coding people. 
2. I can't make my own folder work. The folder shows in the list below Examples, but the content (filenames without space) does not show.
3. I want to be able to classify manually. Now I only see possible hits in the list above the "plate". I would like to have an option where I can see the classification for the individual well, to be able to re-classify. Not all proteins follow a strict one-transition denaturing curve and may need extra attention.
4. I want to look at one row at a time, and would like to have a way to select the whole row without clicking through one by one by shift+click.
5. Sadly, it's also incredibly slow.

**Comment by maciaslab** [comment]
Hi, frkbustad.
I am Pau Martin, thank you for your suggestions and feedback. 

1. About the spaces and filename, I will have a look at this. This is not intended and I am unable to reproduce it. Could you please send me more information about this issue?
2. What type of files do you have in your folder? Could you send me a sample of the files (one should be enough) to xxxxxxx@xxxxxxxxxxx?
3. Each well in the plate can be right-clicked to classify it, without having to search for it in the top list. You can left-click each well to check the curves for it, even the ones classified as "Neutral".
4. The intention of the software is assisting in high-throughput screening by DSF, this is not a general purpose DSF plate analysis software. But we do not rule out  to release a package for a more careful analysis of single plates. But, again, we feel this request is out of the scope for this project.
5. Could you give me some information about the OS and computer you are using? This would help me isolate the problems. The program should not be incredibly slow.
